from selenium.webdriver.common.by import By

class TestLocators:
    NAME_REGISTRATION_FIELD = By.XPATH, ".//*[text()='Имя']/following-sibling::input"
    EMAIL_REGISTRATION_FIELD = By.XPATH, ".//*[text()='Email']/following-sibling::input"
    PASSWORD_REGISTRATION_FIELD = By.XPATH, ".//*[text()='Пароль']/following-sibling::input"
    REGISTRATION_REGISTRATION_BUTTON = By.XPATH, ".//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']"
    WRONGPASS_REGISTARTION_TEXT = By.XPATH, "//*[contains(text(), 'Некорректный пароль')]"
    EXISTUSER_REGISTRATION_TEXT = By.CLASS_NAME, "input__error text_type_main-default"
    ENTER_TO_ACCOUNT_BUTTON = By.XPATH, ".//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg']"
    PUSH_ENTER_BUTTON = By.XPATH, ".//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']"
    LK_BUTTON_2 = By.LINK_TEXT, "Личный Кабинет"
    LK_BUTTON = By.CLASS_NAME, "AppHeader_header__linkText__3q_va.ml-2"
    EXIT_IN_LK_TEXT = By.XPATH, ".//*[contains(text(), 'Выход')]"
    TRASH_PASSWORD_BUTTON = By.XPATH, ".//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg']"
    PUSH_RESET_PASSWORD_TEXT = By.LINK_TEXT, "Восстановить пароль"
    ENTER_AFTER_RESET_PASS_LINK = By.LINK_TEXT, "Войти"
    BUILD_BURGER_CLICK = By.CLASS_NAME, "AppHeader_header__linkText__3q_va.ml-2"
    BUILD_BURGER_TEXT = By.XPATH, "text.text_type_main-large.mb-5.mt-10"
    LOGOUT_BUTTON = By.CLASS_NAME, "Account_button__14Yp3.text.text_type_main-medium.text_color_inactive"
    ENTER_BUTTON_TEXT = By.XPATH, "//*[contains(text(), 'Вход')]"
    CONSTRUCTOR_BULKI = By.XPATH, ".//*[contains(text(), 'Булки')]"
    CONSTRUCTOR_SOUS = By.XPATH, ".//*[contains(text(), 'Соусы')]"
    CONSTRUCTOR_NACHINKI = By.XPATH, ".//*[contains(text(), 'Начинки')]"
    TEST_BURGER = By.CLASS_NAME, "text.text_type_main-large.mb-5.mt-10"
    ЕNTER_AFTER_REG = By.XPATH, "//*[contains(text(), 'Войти')]"
    SCROL_TAB_TAB = By.CLASS_NAME, "tab_tab__1SPyG.tab_tab_type_current__2BEPc.pt-4.pr-10.pb-4.pl-10.noselect"
